package com.tqt.personal_finance_tracking.contants;

public class Contants {

    public static final String PROMPT_EXTRACT_TEXT_VI = "Phân tích đoạn văn bản dưới đây để trích xuất thông tin chi tiêu và xuất ra chuỗi JSON với các trường:'title' : là nội dung chính của chi tiêu, 'fundType' : một trong ['Income', 'Expenses'] để nhận diện loại của nguồn tiền vào hoặc ra, 'type': Một trong ['Housing', 'Food & Dining', 'Transportation', 'Medicine', 'Family Support', 'Investments', 'Books', 'Learning', 'Entertainment', 'Charity', 'Hair Cut', 'Shopping', 'Unknow', 'Salary', 'Repayment']. 'amount': Số tiền đã chi tiêu (định dạng số nguyên VNĐ). 'dateType': Một trong ['Today', 'Yesterday', 'None'] (xác định dựa trên từ khóa liên quan đến ngày). 'note': Thông tin thêm ngoài nội dung chi tiêu chính, ví dụ như gửi xe... . Đoạn văn bản cần phân tích: '%s' Yêu cầu đầu ra (JSON): Ví dụ: Đoạn văn: 'Cơm trưa 35k hôm nay gửi xe 5k' Kết quả: {'title' : 'Cơm trưa', 'fundType' : 'Expenses', 'type': 'Food & Dining', 'amount': '40000', 'dateType': 'Today', 'note': 'gửi xe 5k'} Đoạn văn: 'Mua sách 120k' Kết quả: {'title' : 'Mua sách', 'type': 'Books', 'fundType' : 'Expenses', 'amount': '120000', 'dateType': 'None', 'note': 'mua sách'} Đoạn văn: 'nhận lương 15tr' Kết quả: {'title' : 'Nhận lương', 'type': 'Salary', 'fundType' : 'Income', 'amount': '15000000', 'dateType': 'None', 'note': ''}. Hãy nhớ rằng chỉ trả về chuỗi json và không có bất kì kí tự nào khác.";
    public static final String PROMPT_EXTRACT_TEXT = "Analyze the following text to extract spending information and output a JSON string with the fields: 'title': the main content of the expense or income. 'fundType': one of ['Income', 'Expenses'] to identify the type of incoming or outgoing money. 'type': one of ['Housing', 'Food & Dining', 'Transportation', 'Medicine', 'Family Support', 'Investments', 'Books', 'Learning', 'Entertainment', 'Charity', 'Hair Cut', 'Shopping', 'Unknow', 'Salary', 'Repayment']. 'amount': the amount spent (formatted as an integer in VND). 'dateType': one of ['Today', 'Yesterday', 'None'] (determined by keywords related to the date). 'note': additional information outside the main expense or income content, e.g., parking fees. Text to analyze: '%s' Output format (JSON): For example: Text: 'Cơm trưa 35k hôm nay gửi xe 5k' Result: {'title': 'Cơm trưa', 'fundType': 'Expenses', 'type': 'Food & Dining', 'amount': '40000', 'dateType': 'Today', 'note': 'gửi xe 5k'} Text: 'Mua sách 120k' Result: {'title': 'Mua sách', 'fundType': 'Expenses', 'type': 'Books', 'amount': '120000', 'dateType': 'None', 'note': 'mua sách'} Text: 'nhận lương 15tr' Result: {'title': 'Nhận lương', 'fundType': 'Income', 'type': 'Salary', 'amount': '15000000', 'dateType': 'None', 'note': ''} Remember to return only the JSON string without any extra characters.";

    public static final String DATABASE_INCOME_ID = "15c0d9d80cda81f4bbf6ee9c948c875c";
    public static final String DATABASE_EXPESENS_ID = "15c0d9d80cda8109a136cf5f627eef51";
}
